### ISSUE TITLE
[Inquiry] Similar Project With A11 Base

### ISSUE THREAD

**Issue by jasonmerc** [Project-Mushroom/platform_manifest#22]
I can't tell you how badly I want to build this for my phone... but my G Fast (G8) doesn't have Android 12 sources yet for ROMs.  Are there any plans to have an Android 11 version?  Or perhaps, you can at least point me to a similar project that does work on Android 11?

I did exthmUI already but that project got abandoned a couple days after I ported it.

**Comment by AmeChanRain** [comment]
Sorry, we don't have any plan for Miku UI on Android 11. Maybe you should try to upgrade device configuration by yourself. OwO

Best wishes.
